routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\PasswordController;
use App\Http\Controllers\Admin\QuotationsController;
use App\Http\Controllers\Admin\SearchController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Instructor\GoogleSheetController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


/* Authentication Routes... */

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('login');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware('auth')->group(function () {

    /* Dashboard Route */
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    // Change password routes...
    Route::get('/change/password', [PasswordController::class, 'edit'])->name('password.change');
    Route::post('/change/password', [PasswordController::class, 'update'])->name('password.change.post');
});

Route::group(['middleware' => ['auth', 'preventBackHistory', 'admin']], function () {

    /* Dashboard Route */


    /* Student Routes... */
    Route::resource('students', App\Http\Controllers\Admin\StudentController::class);
    Route::resource('instructors', App\Http\Controllers\Admin\InstructorController::class);
    Route::resource('sheets', App\Http\Controllers\Admin\GoogleSheetController::class);

    /* Search Route... */
    Route::get('search', [SearchController::class, 'search'])->name('search');
});

/*  Common Auth Routes... */
Route::prefix('user')->as('user.')->middleware(['auth', 'preventBackHistory', 'user'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'user'])->name('dashboard');

    Route::resource('sheets', GoogleSheetController::class);

    /*  Change Password Routes... */
    // Route::get('/profile/change-password', [App\Http\Controllers\Auth\ChangePasswordController::class, 'index'])->name('password.change');
    // Route::put('/profile/update-password', [App\Http\Controllers\Auth\ChangePasswordController::class, 'update'])->name('password.update');

});

// Auth::routes();

app/Models/GoogleSheet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GoogleSheet extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'course_name', 'sheet_link', 'month'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/GoogleSheetController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\GoogleSheet;
use Illuminate\Http\Request;

class GoogleSheetController extends Controller
{
    public function index()
    {
        $googleSheets = GoogleSheet::orderBy('id', 'desc')->paginate(5);
        return view('admin.googleSheets.index', compact('googleSheets'));
    }

    public function create()
    {
        abort(404);


        return view('admin.googleSheets.create');
    }

    public function store(Request $request)
    {
        abort(404);


        $validated = $request->validate([
            'course_name' => 'required',
            'sheet_link' => 'required',
            'month' => 'required',
        ]);

        $validated['user_id'] = auth()->user()->id;
        GoogleSheet::create($validated);
        // return back()->with('error', 'Failed to save record');
        return redirect()->route('sheets.index')->with('success', 'Record saved successfully');
    }

    public function show($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        return view('admin.googleSheets.show', compact('googleSheet'));
    }

    public function edit($id)
    {
        abort(404);


        $googleSheet = GoogleSheet::findOrFail($id);
        return view('googleSheets.edit', compact('googleSheet'));
    }

    public function update(Request $request, $id)
    {
        abort(404);


        $googleSheet = GoogleSheet::findOrFail($id);
        $validated = $request->validate([
            'course_name' => 'required',
            'sheet_link' => 'required',
            'month' => 'required',
        ]);
        $googleSheet->update($validated);
        return redirect()->route('sheets.index')->with('success', 'Record updated successfully');
    }

    public function destroy($id)
    {
        abort(404);

        
        $googleSheet = GoogleSheet::findOrFail($id);
        $googleSheet->delete();
        return redirect()->route('user.sheets.index')->with('success', 'Record deleted successfully');
    }
}

app/Http/Controllers/Instructor/GoogleSheetController.php
<?php

namespace App\Http\Controllers\Instructor;

use App\Http\Controllers\Controller;
use App\Models\GoogleSheet;
use Illuminate\Http\Request;

class GoogleSheetController extends Controller
{
    public function index()
    {
        $googleSheets = GoogleSheet::orderBy('id', 'desc')->where('user_id', auth()->user()->id)->paginate(5);
        return view('googleSheets.index', compact('googleSheets'));
    }

    public function create()
    {
        return view('googleSheets.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'course_name' => 'required',
            'sheet_link' => 'required',
            'month' => 'required',
        ]);

        $validated['user_id'] = auth()->user()->id;
        GoogleSheet::create($validated);
        // return back()->with('error', 'Failed to save record');
        return redirect()->route('user.sheets.index')->with('success', 'Record saved successfully');
    }

    public function show($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        return view('googleSheets.show', compact('googleSheet'));
    }

    public function edit($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        return view('googleSheets.edit', compact('googleSheet'));
    }

    public function update(Request $request, $id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        $validated = $request->validate([
            'course_name' => 'required',
            'sheet_link' => 'required',
            'month' => 'required',
        ]);
        $googleSheet->update($validated);
        return redirect()->route('user.sheets.index')->with('success', 'Record updated successfully');
    }

    public function destroy($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        $googleSheet->delete();
        return redirect()->route('user.sheets.index')->with('success', 'Record deleted successfully');
    }
}

resources/views/googleSheets/create.blade.php
@extends('layouts.user', ['activePage' => 'googleSheetCreate', 'pageTitle' => __('New Google Sheet')])
@section('css')
    <style>
        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        input,
        select {
            background-color: #F3F5F7 !important;
        }

        select option {
            padding: 10px;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6">
                    <h1 class="fw-bold" style="font-family: Arial, Helvetica, sans-serif">{{ __('New Google Sheet') }}</h1>
                </div>
                <div class="col-md-6 text-end mb-3">
                    <a href="{{ route('user.sheets.index') }}" class="btn btn-secondary">
                        Back
                    </a>
                </div>
                <section class="section dashboard mt-4">
                    <!-- check for validation errors -->
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('user.sheets.store') }}" method="post">
                        @csrf

                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend>Course Name</legend>
                                <input type="text" name="course_name" class="name"
                                    placeholder="programming fundamental" value="{{ old('course_name') }}">
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <legend>Month / Year Created</legend>
                                <input type="month" name="month" class="name" value="{{ old('month') }}">
                            </div>
                        </div>
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend>Link To Google Sheet</legend>
                                <input type="url" name="sheet_link" class="name" value="{{ old('sheet_link') }}">
                            </div>
                        </div>
                        <div class="buttons_group mt-4 mb-5">
                            <div class="buttons_group1">
                                <button type="submit" class="generate">Generate</button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </main>
@endsection
@section('scripts')
@endsection

resources/views/googleSheets/edit.blade.php
@extends('layouts.user', ['activePage' => 'googleSheets', 'pageTitle' => __('Edit Google Sheet')])
@section('css')
    <style>
        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        input,
        select {
            background-color: #F3F5F7 !important;
        }

        select option {
            padding: 10px;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6">
                    <h1>{{ __('Edit Google Sheet') }}</h1>
                </div>
                <div class="col-md-6 text-end mb-3">
                    <a href="{{ route('user.sheets.index') }}" class="btn btn-secondary">
                        Back
                    </a>
                </div>
                <section class="section dashboard mt-4">
                    <!-- check for validation errors -->
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('user.sheets.update', $googleSheet->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend>Course Name</legend>
                                <input type="text" name="course_name" class="name"
                                    placeholder="programming fundamental"
                                    value="{{ old('course_name') ?? $googleSheet->course_name }}">
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <legend>Month / Year Created</legend>
                                <input type="month" name="month" class="name"
                                    value="{{ old('month') ?? $googleSheet->month }}">
                            </div>
                        </div>
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend>Link To Google Sheet</legend>
                                <input type="url" name="sheet_link" class="name"
                                    value="{{ old('sheet_link') ?? $googleSheet->sheet_link }}">
                            </div>
                        </div>
                        <div class="buttons_group mt-4 mb-5">
                            <div class="buttons_group1">
                                <button type="submit" class="generate">Update</button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </main>
@endsection
@section('scripts')
@endsection

resources/views/googleSheets/index.blade.php
@extends('layouts.user', ['activePage' => 'teachers', 'pageTitle' => __('Google Sheets')])
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">
    <style>
        .plus-icon {
            padding: 4px 7px;
            /* background-color: #17c914; */
            background-color: #198754;
            border-radius: 9px;
            margin-right: 5px !important;
            padding-bottom: 6px !important;
            color: white;
        }

        .pagination {
            width: fit-content;
            float: right;
        }

        .pagination>li>a {
            background-color: white;
            color: #5A4181;
            font-weight: 600;
            margin-left: 12px !important;
            box-shadow: none !important;
            width: 38px !important;
            height: 35px !important;
            border-radius: 0px !important;
        }

        .pagination>li>a:focus,
        .pagination>li>a:hover,
        .pagination>li>span:focus,
        .pagination>li>span:hover {
            color: black;
            border-color: white;
        }

        .pagination>.active>a {
            color: white;
            background-color: #BB1A1A !important;
            border: solid 1px #BB1A1A !important;
        }

        .pagination>.active>a:hover {
            background-color: #BB1A1A !important;
            border: solid 1px #BB1A1A;
        }

        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6 mb-2">
                    <h2>{{ __('Google Sheets List') }}</h2>
                </div>
                <div class="d-flex col-md-6 justify-content-end mb-3 gap-2 position-relative">
                    {{-- <input type="text" name="search" class="name border w-50" placeholder="Search"> --}}
                    {{-- <i class="bi bi-search text-secondary position-absolute top-50 translate-middle-y" style="right:200px"></i> --}}

                    {{-- <a href="{{ route('user.sheets.create') }}" class="btn text-white" style="background-color:#D1884B">
                        Add Google Sheet
                    </a> --}}
                </div>
                <div class="table-responsive">
                    <table class="table invoiceTable table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Course</th>
                                <th>Month</th>
                                <th>Google Sheet Link</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($googleSheets as $sheet)
                            <tr>
                                <td style="5%">{{ $loop->iteration }}</td>
                                <td style="width: 20%">{{ $sheet->course_name }}</td>
                                <td style="width: 15%">{{ $sheet->month }}</td>
                                <td style="width: 30%;word-break:break-word">
                                    {{ $sheet->sheet_link }}
                                </td>
                                <td>
                                    {{-- <a href="{{ route('user.sheets.edit', $sheet->id) }}" title="Edit">
                                        <span class="edit"><i class="bi bi-pencil-square"></i></span>
                                    </a> --}}
                                    <a href="{{ route('user.sheets.show', $sheet->id) }}"  class="btn btn-sm btn-primary rounded">View Sheet</a>
                                    {{-- <button class="border-0" data-bs-toggle="modal" data-bs-target="#deleteGuestModal{{ $sheet->id }}"> <span class="delete"><i
                                                class="bi bi-trash"></i></span>
                                    </button> --}}
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td colspan="9">No record found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                {{-- Adding custom pagination --}}
                {{ $googleSheets->links('pagination::custom') }}
            </div>
        </div>
    </main>
@endsection
@section('modals')
    @foreach ($googleSheets as $sheet)
        {{-- delete sheet confirmation modal --}}
        <div class="modal fade" id="deleteGuestModal{{ $sheet->id }}" tabindex="-1"
            aria-labelledby="deleteGuestModal{{ $sheet->id }}Label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteGuestModal{{ $sheet->id }}Label">Warning!</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {{-- form for deleting sheet --}}
                    <form id="deleteGuestForm" action="{{ route('user.sheets.destroy', $sheet->id) }}" method="POST">
                        @csrf
                        @method('delete')
                        <div class="modal-body">
                            Are you sure you want to delete this record?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            <button type="submit" class="btn btn-danger">Yes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endforeach
@endsection

resources/views/googleSheets/show.blade.php
{{-- @extends('layouts.user', ['activePage' => 'googleSheets', 'pageTitle' => __('Google Sheet Details')])
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">
    <style>
        .plus-icon {
            padding: 4px 7px;
            /* background-color: #17c914; */
            background-color: #198754;
            border-radius: 9px;
            margin-right: 5px !important;
            padding-bottom: 6px !important;
            color: white;
        }

        .btn-check:checked+.btn {
            background-color: #D0874C;
        }

        .btn-outline-primary {
            border: 1px solid black !important;
            outline: none !important;
            box-shadow: none !important;
        }

        .btn-outline-primary:focus {
            border: 1px solid black !important;
            outline: none !important;
            box-shadow: none !important;
        }

        .btn-outline-primary:hover {
            border: 1px solid black !important
        }

        .btn-check+.btn {
            color: black;
        }

        .btn-check:checked+.btn {
            color: white !important;
        }

        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;

        }
    </style>
@endsection
@section('content')
    <main id="main" style="overflow: auto!important">
        <div class="main-box bg-white mb-5 rounded-5">
            <div class="row invoiceList mt-2">
                <div class="col-md-6 my-2">
                    <h2>Hello 👋 Mr. <span class="text-capitalize">{{ auth()->user()->name }}</span>
                    </h2>
                </div>
                <div style="overflow:auto">
                    <iframe
                        src="{{ $googleSheet->sheet_link }}"
                        frameborder="0" width="100%" height="800"></iframe>
                </div>
            </div>
        </div>
    </main>
@endsection
@section('scripts')
    <script>
        var present = document.getElementById('present');
        var absent = document.getElementById('absent');
        var presentLabel = document.getElementById('presentLabel');
        var absentLabel = document.getElementById('absentLabel');

        presentLabel.addEventListener('mouseover', function() {
            if (present.checked == false && absent.checked == false) {
                presentLabel.style.color = 'black';
                absentLabel.style.color = 'black';
            }
        });
    </script>
@endsection --}}

@extends('layouts.user', ['activePage' => 'googleSheets', 'pageTitle' => __('Google Sheet Details')])
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">
    <style>
        .plus-icon {
            padding: 4px 7px;
            /* background-color: #17c914; */
            background-color: #198754;
            border-radius: 9px;
            margin-right: 5px !important;
            padding-bottom: 6px !important;
            color: white;
        }

        .pagination {
            width: fit-content;
            float: right;
        }

        .pagination>li>a {
            background-color: white;
            color: #5A4181;
            font-weight: 600;
            margin-left: 12px !important;
            box-shadow: none !important;
            width: 38px !important;
            height: 35px !important;
            border-radius: 0px !important;
        }

        .pagination>li>a:focus,
        .pagination>li>a:hover,
        .pagination>li>span:focus,
        .pagination>li>span:hover {
            color: black;
            border-color: white;
        }

        .pagination>.active>a {
            color: white;
            background-color: #BB1A1A !important;
            border: solid 1px #BB1A1A !important;
        }

        .pagination>.active>a:hover {
            background-color: #BB1A1A !important;
            border: solid 1px #BB1A1A;
        }

        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6">
                    <h2>{{ $googleSheet->course_name }} - {{ $googleSheet->month }}</h2>
                </div>
                <div class="d-flex col-md-6 justify-content-end mb-3 gap-2 position-relative">
                    <a href="{{ route('user.sheets.edit', $googleSheet->id) }}" class="btn btn-primary">
                        Edit
                    </a>
                    <a href="javascript:void(0)" type="button" data-bs-toggle="modal" data-bs-target="#deleteSheetModal" class="btn btn-danger">
                        Delete
                    </a>
                </div>
                <div class="col-md-12">
                    <div style="overflow:auto">
                        <iframe
                            src="{{ $googleSheet->sheet_link }}"
                            frameborder="0" width="100%" height="800"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </main>
@endsection
@section('modals')
        {{-- delete sheet confirmation modal --}}
        <div class="modal fade" id="deleteSheetModal" tabindex="-1"
            aria-labelledby="deleteSheetModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteSheetModalLabel">Warning!</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {{-- form for deleting sheet --}}
                    <form id="deleteSheetForm" action="{{ route('user.sheets.destroy', $googleSheet->id) }}" method="POST">
                        @csrf
                        @method('delete')
                        <div class="modal-body">
                            Are you sure you want to delete this sheet?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            <button type="submit" class="btn btn-danger">Yes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
@endsection