routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\InvoiceController;
use App\Http\Controllers\Admin\PasswordController;
use App\Http\Controllers\Admin\QuotationsController;
use App\Http\Controllers\Admin\SearchController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Instructor\GoogleSheetController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


/* Authentication Routes... */

Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'login'])->name('login');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::middleware('auth')->group(function () {

    /* Dashboard Route */
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');

    // Change password routes...
    Route::get('/change/password', [PasswordController::class, 'edit'])->name('password.change');
    Route::post('/change/password', [PasswordController::class, 'update'])->name('password.change.post');
});

Route::group(['middleware' => ['auth', 'preventBackHistory', 'admin']], function () {

    /* Dashboard Route */


    /* Student Routes... */
    Route::resource('students', App\Http\Controllers\Admin\StudentController::class);
    Route::resource('instructors', App\Http\Controllers\Admin\InstructorController::class);
    Route::resource('sheets', App\Http\Controllers\Admin\GoogleSheetController::class);

    /* Search Route... */
    Route::get('search', [SearchController::class, 'search'])->name('search');
});

/*  Common Auth Routes... */
Route::prefix('user')->as('user.')->middleware(['auth', 'preventBackHistory', 'user'])->group(function () {

    Route::get('/dashboard', [DashboardController::class, 'user'])->name('dashboard');

    Route::resource('sheets', GoogleSheetController::class);

    /*  Change Password Routes... */
    // Route::get('/profile/change-password', [App\Http\Controllers\Auth\ChangePasswordController::class, 'index'])->name('password.change');
    // Route::put('/profile/update-password', [App\Http\Controllers\Auth\ChangePasswordController::class, 'update'])->name('password.update');

});

// Auth::routes();

app/Http/Controllers/Admin/InstructorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class InstructorController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $instructors = User::orderBy('id', 'desc')->where('role', 'user')->paginate(5);
        return view('instructors.index', compact('instructors'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('instructors.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'required',
        ]);

        User::create([
            'name' => $validated['name'],
            'email' => $validated['email'],
            'password' => bcrypt($validated['password']),
            'role' => 'user',
        ]);
        // return back()->with('error', 'Failed to save student');
        return redirect()->route('instructors.index')->with('success', 'Student created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $student = User::find($id);
        return view('instructors.show', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $instructor)
    {
        return view('instructors.edit', compact('instructor'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $instructor)
    {
        $validated = $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'nullable',
        ]);

        $instructor->name = $validated['name'];
        $instructor->email = $validated['email'];
        if($request->password != null && $request->password != ""){
            $instructor->password = bcrypt($request->password);
        }
        $updated = $instructor->save();

        if ($updated) {
            return redirect()->route('instructors.index')->with('success', 'Record updated successfully');
        }
        return back()->with('error', 'Failed to update record');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $instructor = User::findOrFail($id);
        $deleted = $instructor->delete();
        if ($deleted) {
            return redirect()->route('instructors.index')->with('success', 'Record deleted successfully');
        }
        return back()->with('error', 'Failed to delete record');
    }
}

app/Http/Controllers/Instructor/GoogleSheetController.php
<?php

namespace App\Http\Controllers\Instructor;

use App\Http\Controllers\Controller;
use App\Models\GoogleSheet;
use Illuminate\Http\Request;

class GoogleSheetController extends Controller
{
    public function index()
    {
        $googleSheets = GoogleSheet::orderBy('id', 'desc')->where('user_id', auth()->user()->id)->paginate(5);
        return view('googleSheets.index', compact('googleSheets'));
    }

    public function create()
    {
        return view('googleSheets.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'course_name' => 'required',
            'sheet_link' => 'required',
            'month' => 'required',
        ]);

        $validated['user_id'] = auth()->user()->id;
        GoogleSheet::create($validated);
        // return back()->with('error', 'Failed to save record');
        return redirect()->route('user.sheets.index')->with('success', 'Record saved successfully');
    }

    public function show($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        return view('googleSheets.show', compact('googleSheet'));
    }

    public function edit($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        return view('googleSheets.edit', compact('googleSheet'));
    }

    public function update(Request $request, $id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        $validated = $request->validate([
            'course_name' => 'required',
            'sheet_link' => 'required',
            'month' => 'required',
        ]);
        $googleSheet->update($validated);
        return redirect()->route('user.sheets.index')->with('success', 'Record updated successfully');
    }

    public function destroy($id)
    {
        $googleSheet = GoogleSheet::findOrFail($id);
        $googleSheet->delete();
        return redirect()->route('user.sheets.index')->with('success', 'Record deleted successfully');
    }
}

resources/views/instructors/create.blade.php
@extends('layouts.app', ['activePage' => 'teachers', 'pageTitle' => __('New Instructor')])
@section('css')
    <style>
        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        input,
        select {
            background-color: #F3F5F7 !important;
        }

        select option {
            padding: 10px;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6">
                    <h1 class="fw-bold" style="font-family: Arial, Helvetica, sans-serif">{{ __('New Instructor') }}</h1>
                </div>
                <div class="col-md-6 text-end mb-3">
                    <a href="{{ route('instructors.index') }}" class="btn btn-secondary">
                        Back
                    </a>
                </div>
                <section class="section dashboard mt-4">
                    <form action="{{ route('instructors.store') }}" method="post">
                        @csrf
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend for="name">Instructor Name</legend>
                                <input type="text" id="name" name="name" class="name" placeholder="Name"
                                    value="{{ old('name') }}">
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <legend for="nothing">Email</legend>
                                <input type="email" id="email" name="email" class="name"
                                    placeholder="example@mail.com" value="{{ old('email') }}">
                            </div>
                        </div>
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend for="nothing">Password</legend>
                                <input type="password" class="name" name="password">
                            </div>
                        </div>
                        <div class="buttons_group mt-4 mb-5">
                            <div class="buttons_group1">
                                <button type="submit" class="generate">Save</button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </main>
@endsection
@section('scripts')
    <script></script>
@endsection

resources/views/instructors/edit.blade.php
@extends('layouts.app', ['activePage' => 'teachers', 'pageTitle' => __('New Teacher')])
@section('css')
    <style>
        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        input,
        select {
            background-color: #F3F5F7 !important;
        }

        select option {
            padding: 10px;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6">
                    <h1 class="fw-bold" style="font-family: Arial, Helvetica, sans-serif">{{ __("Edit Instructor's Data") }}</h1>
                </div>
                <div class="col-md-6 text-end mb-3">
                    <a href="{{ route('instructors.index') }}" class="btn btn-secondary">
                        Back
                    </a>
                </div>
                <section class="section dashboard mt-4">
                    <form action="{{ route('instructors.update', $instructor->id) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend for="name">Instructor Name</legend>
                                <input type="text" id="name" name="name" class="name" placeholder="Name"
                                    value="{{ old('name') ?? $instructor->name }}">
                            </div>
                            <div class="col-12 col-md-6 mb-3">
                                <legend for="email">Email</legend>
                                <input type="text" id="email" name="email" class="name"
                                    placeholder="example@mail.com" value="{{ old('email') ?? $instructor->email }}">
                            </div>
                        </div>
                        <div class="row inputs">
                            <div class="col-12 col-md-6 mb-3">
                                <legend for="password">Password</legend>
                                <input type="text" class="name" name="password">
                            </div>
                        </div>
                        <div class="buttons_group mt-4 mb-5">
                            <div class="buttons_group1">
                                <button type="submit" class="generate">Update</button>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </main>
@endsection
@section('scripts')
    <script></script>
@endsection

resources/views/instructors/index.blade.php
@extends('layouts.app', ['activePage' => 'teachers', 'pageTitle' => __('Instructors')])
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">
    <style>
        .plus-icon {
            padding: 4px 7px;
            /* background-color: #17c914; */
            background-color: #198754;
            border-radius: 9px;
            margin-right: 5px !important;
            padding-bottom: 6px !important;
            color: white;
        }

        .pagination {
            width: fit-content;
            float: right;
        }

        .pagination>li>a {
            background-color: white;
            color: #5A4181;
            font-weight: 600;
            margin-left: 12px !important;
            box-shadow: none !important;
            width: 38px !important;
            height: 35px !important;
            border-radius: 0px !important;
        }

        .pagination>li>a:focus,
        .pagination>li>a:hover,
        .pagination>li>span:focus,
        .pagination>li>span:hover {
            color: black;
            border-color: white;
        }

        .pagination>.active>a {
            color: white;
            background-color: #BB1A1A !important;
            border: solid 1px #BB1A1A !important;
        }

        .pagination>.active>a:hover {
            background-color: #BB1A1A !important;
            border: solid 1px #BB1A1A;
        }

        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="col-md-6">
                    <h2>{{ __('Instructors List') }}</h2>
                </div>
                <div class="d-flex col-md-6 justify-content-end mb-3 gap-2 position-relative">
                    <a href="{{ route('instructors.create') }}" class="btn text-white" style="background-color:#D1884B">
                        New Instructor
                    </a>
                </div>
                <div class="table-responsive">
                    <table class="table invoiceTable table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Instructor Name</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($instructors as $student)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $student->name }}</td>
                                    <td>{{ $student->email }}</td>
                                    <td>
                                        <a href="{{ route('instructors.edit', $student->id) }}" title="Edit">
                                            <span class="edit"><i class="bi bi-pencil-square"></i></span>
                                        </a>
                                        <a href="{{ route('instructors.show', $student->id) }}" title="Details"><span
                                                class="eye"><i class="bi bi-eye"></i></span></a>
                                        <button data-bs-toggle="modal"
                                            data-bs-target="#deleteGuestModal{{ $student->id }}" title="Delete"
                                            class="deleteIcon">
                                            <span class="delete"><i class="bi bi-trash"></i></span>
                                        </button>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="9">No Instructor Found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                {{-- Adding custom pagination --}}
                {{ $instructors->links('pagination::custom') }}
            </div>
        </div>
    </main>
@endsection
@section('modals')
    @foreach ($instructors as $student)
        {{-- delete student confirmation modal --}}
        <div class="modal fade" id="deleteGuestModal{{ $student->id }}" tabindex="-1"
            aria-labelledby="deleteGuestModal{{ $student->id }}Label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteGuestModal{{ $student->id }}Label">Warning!</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    {{-- form for deleting student --}}
                    <form id="deleteGuestForm" action="{{ route('instructors.destroy', $student->id) }}" method="POST">
                        @csrf
                        @method('delete')
                        <div class="modal-body">
                            Are you sure you want to delete this instructor's data?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            <button type="submit" class="btn btn-danger">Yes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    @endforeach
@endsection

resources/views/instructors/show.blade.php
@extends('layouts.app', ['activePage' => 'teachers', 'pageTitle' => __('Teacher Details')])

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/css/dashboard.css') }}">
    <style>
        .main-box {
            max-width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }
    </style>
@endsection
@section('content')
    <main id="main">
        {{-- Guest Details --}}
        <div class="main-box bg-white">
            <div class="row invoiceList mt-2">
                <div class="row mb-3 d-flex align-items-center pe-0">
                    <div class="col-md-6">
                        <h2>{{ __('Instructor Details') }}</h2>
                    </div>
                    <div class="col-md-6 text-end pe-0">
                        <a href="{{ url()->previous() }}" class="btn btn-secondary">
                            Back
                        </a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table">

                        <tbody>
                            <tr>
                                <td class="text-start"><strong>{{ __('Name') }}</strong></td>
                                <td class="text-start">{{ $student->name }}</td>

                            </tr>
                            <tr>
                                <td class="text-start"><strong>{{ __('Email') }}</strong></td>
                                <td class="text-start">{{ $student->email }}</td>

                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {{-- Guest Payment Details --}}
        <div class="main-box bg-white mt-3">
            <div class="row invoiceList mt-2">
                <div class="row mb-3 d-flex align-items-center pe-0">
                    <div class="col-md-6">
                        <h2>{{ __('Attendance Details') }}</h2>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table invoiceTable table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Attendance Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($student->invoices = [] as $invoice)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ \Carbon\Carbon::parse($invoice->invoice_date)->format('d M Y') }}</td>
                                    <td>
                                        <button class="{{ $invoice->status === 'Received' ? 'present' : 'absent' }}">
                                            {{ $invoice->status === 'Received' ? 'Present' : 'Absent' }}
                                        </button>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="9">No Record Found</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
@endsection